apiVersion: v1
kind: Service
metadata:
  name: api-demo-service
spec:
  type: NodePort  # Use NodePort for external access
  selector:
    app: api-demo
  ports:
    - port: 3000          # The port that your container listens on (targetPort)
      targetPort: 3000     # This matches the port in your Dockerfile
      nodePort: 30001      # The port you want to access externally (NodePort)
